In [75]:
import pandas as pd
import numpy as np

In [76]:
df=pd.read_csv('/content/reviews_dataset.csv')

In [77]:
df.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [78]:
df.shape

(2225, 2)

In [79]:
df

news      type
0     China had role in Yukos split-up\n \n China le...  business
1     Oil rebounds from weather effect\n \n Oil pric...  business
2     Indonesia 'declines debt freeze'\n \n Indonesi...  business
3     $1m payoff for former Shell boss\n \n Shell is...  business
4     US bank in $515m SEC settlement\n \n Five Bank...  business
...                                                 ...       ...
2220  Microsoft launches its own search\n \n Microso...      tech
2221  Warnings about junk mail deluge\n \n The amoun...      tech
2222  Microsoft gets the blogging bug\n \n Software ...      tech
2223  Gamers snap up new Sony PSP\n \n Gamers have b...      tech
2224  Apple laptop is 'greatest gadget'\n \n The App...      tech

[2225 rows x 2 columns]

Task 1. Drop words if not alphabats


In [80]:
import re

def remove(news):
    news = re.sub(r'[^a-zA-Z\s]', '', news, re.I|re.A)
    news = re.sub(' +', ' ', news)
    return news


df['cleaned_text'] = df['news'].apply(remove)
df.head()

news      type  \
0  China had role in Yukos split-up\n \n China le...  business   
1  Oil rebounds from weather effect\n \n Oil pric...  business   
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business   
3  $1m payoff for former Shell boss\n \n Shell is...  business   
4  US bank in $515m SEC settlement\n \n Five Bank...  business   

                                        cleaned_text  
0  China had role in Yukos splitup\n \n China len...  
1  Oil rebounds from weather effect\n \n Oil pric...  
2  Indonesia declines debt freeze\n \n Indonesia ...  
3  m payoff for former Shell boss\n \n Shell is t...  
4  US bank in m SEC settlement\n \n Five Bank of ...

Task 2. Tokenize the sentences

In [81]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [82]:
def tokenize(clean_text):
    tokens = word_tokenize(clean_text)
    return tokens

df['tokenized_text'] = df['cleaned_text'].apply(tokenize)
df.head()

news      type  \
0  China had role in Yukos split-up\n \n China le...  business   
1  Oil rebounds from weather effect\n \n Oil pric...  business   
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business   
3  $1m payoff for former Shell boss\n \n Shell is...  business   
4  US bank in $515m SEC settlement\n \n Five Bank...  business   

                                        cleaned_text  \
0  China had role in Yukos splitup\n \n China len...   
1  Oil rebounds from weather effect\n \n Oil pric...   
2  Indonesia declines debt freeze\n \n Indonesia ...   
3  m payoff for former Shell boss\n \n Shell is t...   
4  US bank in m SEC settlement\n \n Five Bank of ...   

                                      tokenized_text  
0  [China, had, role, in, Yukos, splitup, China, ...  
1  [Oil, rebounds, from, weather, effect, Oil, pr...  
2  [Indonesia, declines, debt, freeze, Indonesia,...  
3  [m, payoff, for, former, Shell, boss, Shell, i...  
4  [US, bank, in, m, SEC, settlement, Five, Bank,...

Perform lemitization

In [83]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [84]:
# df['cleaned_text'][4]

In [85]:
df['lemat'] = df['cleaned_text'].apply(lemmitize_words)
df.head()

news      type  \
0  China had role in Yukos split-up\n \n China le...  business   
1  Oil rebounds from weather effect\n \n Oil pric...  business   
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business   
3  $1m payoff for former Shell boss\n \n Shell is...  business   
4  US bank in $515m SEC settlement\n \n Five Bank...  business   

                                        cleaned_text  \
0  China had role in Yukos splitup\n \n China len...   
1  Oil rebounds from weather effect\n \n Oil pric...   
2  Indonesia declines debt freeze\n \n Indonesia ...   
3  m payoff for former Shell boss\n \n Shell is t...   
4  US bank in m SEC settlement\n \n Five Bank of ...   

                                      tokenized_text  \
0  [China, had, role, in, Yukos, splitup, China, ...   
1  [Oil, rebounds, from, weather, effect, Oil, pr...   
2  [Indonesia, declines, debt, freeze, Indonesia,...   
3  [m, payoff, for, former, Shell, boss, Shell, i...   
4  [US, bank, in, m, SEC, settlement, Five, Bank,...   

                                               lemat  
0  China have role in Yukos splitup China lend Ru...  
1  Oil rebound from weather effect Oil price reco...  
2  Indonesia decline debt freeze Indonesia no lon...  
3  m payoff for former Shell boss Shell be to pay...  
4  US bank in m SEC settlement Five Bank of Ameri...

Task 03 :Vectorize using bigram and trigram techniques.


In [86]:
from sklearn.feature_extraction.text import CountVectorizer

In [87]:
bi_gram_vectorizer = CountVectorizer(ngram_range=(2,2))

In [88]:
bi_gram = vectorizer.fit_transform(df['lemat'])

In [89]:
bi_gram.shape

(2225, 294971)

In [90]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [91]:
X= df['lemat']
Y= df['type']
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)


In [92]:
bi_gram_vectorizer = CountVectorizer(ngram_range=(2,2))

X_train_n_gram = bi_gram_vectorizer.fit_transform(X_train)
X_test_n_gram = bi_gram_vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf = RandomForestClassifier(n_estimators=150)

rf.fit(X_train_n_gram,y_train)
y_pred = rf.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Shape of X_train_bow: (1780, 251835)
Shape of X_test_bow: (445, 251835)
0.849438202247191
[[108   1   3   3   0]
 [  7  43   0  20   2]
 [  4   0  64   7   1]
 [  0   0   0 102   0]
 [ 10   2   0   7  61]]


tri gram

In [93]:
tri_gram_vectorizer = CountVectorizer(ngram_range=(3,3))

X_train_n_gram = tri_gram_vectorizer.fit_transform(X_train)
X_test_n_gram = tri_gram_vectorizer.transform(X_test)

# Output the shapes of the resulting Bag of Words matrices
print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf = RandomForestClassifier(n_estimators=150)

rf.fit(X_train_n_gram,y_train)
y_pred = rf.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Shape of X_train_bow: (1780, 483325)
Shape of X_test_bow: (445, 483325)
0.7685393258426966
[[ 88   1   2  22   2]
 [  7  39   0  25   1]
 [  3   1  59  11   2]
 [  0   0   0 102   0]
 [  6   2   0  18  54]]


In [96]:
print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

     business       0.85      0.77      0.80       115
entertainment       0.91      0.54      0.68        72
     politics       0.97      0.78      0.86        76
        sport       0.57      1.00      0.73       102
         tech       0.92      0.68      0.78        80

     accuracy                           0.77       445
    macro avg       0.84      0.75      0.77       445
 weighted avg       0.83      0.77      0.77       445

